# Generated by Django 5.1.7 on 2025-04-11 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_updatecode_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatecode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 11, 15, 20, 13, 725748, tzinfo=datetime.timezone.utc)),
        ),
    ]
