# Generated by Django 5.1.7 on 2025-04-15 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_product_type_alter_updatecode_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatecode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 15, 14, 50, 9, 743933, tzinfo=datetime.timezone.utc)),
        ),
    ]
