# Generated by Django 5.1.7 on 2025-04-17 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_updatecode_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('tabak', 'Tabak'), ('kase', 'Kase'), ('karo', 'Karo'), ('vazo', 'Vazo'), ('diğer', 'Diğer')], default='diğer', max_length=50),
        ),
        migrations.AlterField(
            model_name='updatecode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 17, 13, 30, 30, 510249, tzinfo=datetime.timezone.utc)),
        ),
    ]
