# Generated by Django 5.1.7 on 2025-04-17 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_product_type_alter_updatecode_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatecode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 17, 13, 30, 37, 489723, tzinfo=datetime.timezone.utc)),
        ),
    ]
