# Generated by Django 5.1.7 on 2025-04-21 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_updatecode_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatecode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 13, 12, 19, 155107, tzinfo=datetime.timezone.utc)),
        ),
    ]
