# Generated by Django 5.1.7 on 2025-04-22 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_updatecode_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatecode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 20, 59, 20, 40029, tzinfo=datetime.timezone.utc)),
        ),
    ]
